import { describe, expect, test } from "bun:test";
import type { MergedReviewFinding } from "../../workflows/improvinho/projection";

/**
 * Tests for push-findings pure logic: title generation,
 * description formatting, and priority filtering.
 */

function buildMergedFinding(overrides: Partial<MergedReviewFinding> = {}): MergedReviewFinding {
  return {
    id: "finding-1",
    mergeKey: "bug:src-auth-login-ts:handle-login:null-session",
    kind: "bug",
    priority: "high",
    confidence: "high",
    summary: "Null session can escape the login guard",
    evidence: "The handler reads session.user.id before the session null check.",
    primaryFile: "src/auth/login.ts",
    lineRefs: ["src/auth/login.ts:14", "src/auth/login.ts:18"],
    symbol: "handleLogin",
    pattern: "null-check-before-access",
    suggestedDiff: "- const id = session.user.id\n+ if (!session) return null\n+ const id = session.user.id",
    acceptIf: "Session can actually be null at runtime",
    dismissIf: "Type system guarantees non-null session",
    sourceLenses: ["refactor-hunter", "type-system-purist"],
    sourceScopes: ["src/auth/login.ts", "src/auth"],
    supportCount: 2,
    ...overrides,
  };
}

// Re-implement the pure functions to test the contract
// (they are not exported from push-findings.ts)

const PRIORITY_MAP: Record<string, number> = {
  critical: 1,
  high: 2,
  medium: 3,
  low: 4,
};

function findingToTitle(finding: MergedReviewFinding, index: number): string {
  const displayId = `IMP-${String(index + 1).padStart(4, "0")}`;
  return `[${displayId}] ${finding.summary}`;
}

function findingToDescription(finding: MergedReviewFinding): string {
  const lines: string[] = [];
  lines.push(`**Kind:** ${finding.kind}`);
  lines.push(`**Priority:** ${finding.priority}`);
  lines.push(`**Confidence:** ${finding.confidence}`);
  lines.push(`**File:** \`${finding.primaryFile}\``);
  if (finding.lineRefs.length > 0) {
    lines.push(`**Lines:** ${finding.lineRefs.map((r) => `\`${r}\``).join(", ")}`);
  }
  if (finding.symbol) {
    lines.push(`**Symbol:** \`${finding.symbol}\``);
  }
  lines.push("");
  lines.push("## Evidence");
  lines.push(finding.evidence);
  if (finding.acceptIf) {
    lines.push("");
    lines.push(`**Accept if:** ${finding.acceptIf}`);
  }
  if (finding.dismissIf) {
    lines.push("");
    lines.push(`**Dismiss if:** ${finding.dismissIf}`);
  }
  if (finding.suggestedDiff) {
    lines.push("");
    lines.push("## Suggested Fix");
    lines.push("```diff");
    lines.push(finding.suggestedDiff);
    lines.push("```");
  }
  lines.push("");
  lines.push("---");
  lines.push(`*Detected by: ${finding.sourceLenses.join(", ")}*`);
  lines.push(`*Scopes: ${finding.sourceScopes.join(", ")}*`);
  lines.push(`*Support count: ${finding.supportCount}*`);
  lines.push(`*Generated by improvinho*`);
  return lines.join("\n");
}

describe("findingToTitle", () => {
  test("generates zero-padded display ID with summary", () => {
    const finding = buildMergedFinding();
    expect(findingToTitle(finding, 0)).toBe("[IMP-0001] Null session can escape the login guard");
    expect(findingToTitle(finding, 99)).toBe("[IMP-0100] Null session can escape the login guard");
  });
});

describe("findingToDescription", () => {
  test("includes all metadata fields", () => {
    const desc = findingToDescription(buildMergedFinding());

    expect(desc).toContain("**Kind:** bug");
    expect(desc).toContain("**Priority:** high");
    expect(desc).toContain("**Confidence:** high");
    expect(desc).toContain("**File:** `src/auth/login.ts`");
    expect(desc).toContain("**Lines:** `src/auth/login.ts:14`, `src/auth/login.ts:18`");
    expect(desc).toContain("**Symbol:** `handleLogin`");
  });

  test("includes evidence section", () => {
    const desc = findingToDescription(buildMergedFinding());
    expect(desc).toContain("## Evidence");
    expect(desc).toContain("The handler reads session.user.id before the session null check.");
  });

  test("includes accept/dismiss conditions", () => {
    const desc = findingToDescription(buildMergedFinding());
    expect(desc).toContain("**Accept if:** Session can actually be null at runtime");
    expect(desc).toContain("**Dismiss if:** Type system guarantees non-null session");
  });

  test("includes suggested diff in code block", () => {
    const desc = findingToDescription(buildMergedFinding());
    expect(desc).toContain("## Suggested Fix");
    expect(desc).toContain("```diff");
    expect(desc).toContain("- const id = session.user.id");
    expect(desc).toContain("+ if (!session) return null");
  });

  test("includes source attribution", () => {
    const desc = findingToDescription(buildMergedFinding());
    expect(desc).toContain("*Detected by: refactor-hunter, type-system-purist*");
    expect(desc).toContain("*Scopes: src/auth/login.ts, src/auth*");
    expect(desc).toContain("*Support count: 2*");
    expect(desc).toContain("*Generated by improvinho*");
  });

  test("omits optional fields when null", () => {
    const desc = findingToDescription(buildMergedFinding({
      symbol: null,
      lineRefs: [],
      suggestedDiff: null,
      acceptIf: null,
      dismissIf: null,
    }));

    expect(desc).not.toContain("**Symbol:**");
    expect(desc).not.toContain("**Lines:**");
    expect(desc).not.toContain("## Suggested Fix");
    expect(desc).not.toContain("**Accept if:**");
    expect(desc).not.toContain("**Dismiss if:**");
  });
});

describe("PRIORITY_MAP", () => {
  test("maps priority strings to Linear priority numbers", () => {
    expect(PRIORITY_MAP["critical"]).toBe(1);
    expect(PRIORITY_MAP["high"]).toBe(2);
    expect(PRIORITY_MAP["medium"]).toBe(3);
    expect(PRIORITY_MAP["low"]).toBe(4);
  });
});

describe("priority filtering", () => {
  test("filters findings at or above minimum priority", () => {
    const findings = [
      buildMergedFinding({ priority: "critical", summary: "Critical bug" }),
      buildMergedFinding({ priority: "high", summary: "High bug" }),
      buildMergedFinding({ priority: "medium", summary: "Medium issue" }),
      buildMergedFinding({ priority: "low", summary: "Low issue" }),
    ];

    const minPriority = "high";
    const minRank = PRIORITY_MAP[minPriority]!;
    const filtered = findings.filter((f) => (PRIORITY_MAP[f.priority] ?? 4) <= minRank);

    expect(filtered).toHaveLength(2);
    expect(filtered.map((f) => f.priority)).toEqual(["critical", "high"]);
  });

  test("includes all findings when minPriority is low", () => {
    const findings = [
      buildMergedFinding({ priority: "critical" }),
      buildMergedFinding({ priority: "low" }),
    ];

    const minRank = PRIORITY_MAP["low"]!;
    const filtered = findings.filter((f) => (PRIORITY_MAP[f.priority] ?? 4) <= minRank);

    expect(filtered).toHaveLength(2);
  });

  test("only includes critical when minPriority is critical", () => {
    const findings = [
      buildMergedFinding({ priority: "critical" }),
      buildMergedFinding({ priority: "high" }),
      buildMergedFinding({ priority: "medium" }),
    ];

    const minRank = PRIORITY_MAP["critical"]!;
    const filtered = findings.filter((f) => (PRIORITY_MAP[f.priority] ?? 4) <= minRank);

    expect(filtered).toHaveLength(1);
    expect(filtered[0]!.priority).toBe("critical");
  });
});
