/**
 * Push improvinho findings to Linear as individual issues.
 *
 * Reads MergedReviewFinding[] from the improvinho DB and creates
 * one Linear issue per finding with structured metadata.
 */

import { Database } from "bun:sqlite";
import {
  loadMergedFindingsFromDb,
  resolveLatestReviewRunId,
  type MergedReviewFinding,
} from "../../workflows/improvinho/projection";
import { getLinearClient, useLinear } from "smithers-orchestrator/linear";
import type { PushFindingsResult } from "./types";

const PRIORITY_MAP: Record<string, number> = {
  critical: 1, // Urgent
  high: 2,     // High
  medium: 3,   // Medium
  low: 4,      // Low
};

function findingToTitle(finding: MergedReviewFinding, index: number): string {
  const displayId = `IMP-${String(index + 1).padStart(4, "0")}`;
  return `[${displayId}] ${finding.summary}`;
}

function findingToDescription(finding: MergedReviewFinding): string {
  const lines: string[] = [];

  lines.push(`**Kind:** ${finding.kind}`);
  lines.push(`**Priority:** ${finding.priority}`);
  lines.push(`**Confidence:** ${finding.confidence}`);
  lines.push(`**File:** \`${finding.primaryFile}\``);

  if (finding.lineRefs.length > 0) {
    lines.push(`**Lines:** ${finding.lineRefs.map((r) => `\`${r}\``).join(", ")}`);
  }

  if (finding.symbol) {
    lines.push(`**Symbol:** \`${finding.symbol}\``);
  }

  lines.push("");
  lines.push("## Evidence");
  lines.push(finding.evidence);

  if (finding.acceptIf) {
    lines.push("");
    lines.push(`**Accept if:** ${finding.acceptIf}`);
  }

  if (finding.dismissIf) {
    lines.push("");
    lines.push(`**Dismiss if:** ${finding.dismissIf}`);
  }

  if (finding.suggestedDiff) {
    lines.push("");
    lines.push("## Suggested Fix");
    lines.push("```diff");
    lines.push(finding.suggestedDiff);
    lines.push("```");
  }

  lines.push("");
  lines.push("---");
  lines.push(`*Detected by: ${finding.sourceLenses.join(", ")}*`);
  lines.push(`*Scopes: ${finding.sourceScopes.join(", ")}*`);
  lines.push(`*Support count: ${finding.supportCount}*`);
  lines.push(`*Generated by improvinho*`);

  return lines.join("\n");
}

async function resolveLabel(
  existingLabels: { id: string; name: string }[],
  name: string,
): Promise<string | undefined> {
  const existing = existingLabels.find(
    (l) => l.name.toLowerCase() === name.toLowerCase(),
  );
  return existing?.id;
}

export async function pushFindingsToLinear(opts: {
  dbPath: string;
  teamId: string;
  runId?: string;
  /** Only push findings at or above this priority. Default: all. */
  minPriority?: "critical" | "high" | "medium" | "low";
}): Promise<PushFindingsResult> {
  const { dbPath, teamId, minPriority } = opts;
  const db = new Database(dbPath, { readonly: true });

  try {
    const runId = opts.runId ?? resolveLatestReviewRunId(db);
    if (!runId) {
      throw new Error("No review run found in the database.");
    }

    let findings = loadMergedFindingsFromDb(db, runId);

    // Filter by minimum priority if specified
    if (minPriority) {
      const minRank = PRIORITY_MAP[minPriority] ?? 4;
      findings = findings.filter((f) => (PRIORITY_MAP[f.priority] ?? 4) <= minRank);
    }

    if (findings.length === 0) {
      console.log("  No findings to push.");
      return { created: [], skipped: 0 };
    }

    // Use raw SDK client — smithers' useLinear facade lacks createIssue and listLabels
    const client = getLinearClient();
    const linear = useLinear();

    const labelsResult = await client.issueLabels({ first: 100 });
    const labels = labelsResult.nodes.map((l: any) => ({ id: l.id, name: l.name }));

    const created: PushFindingsResult["created"] = [];
    let skipped = 0;

    for (let i = 0; i < findings.length; i++) {
      const finding = findings[i]!;
      const title = findingToTitle(finding, i);
      const description = findingToDescription(finding);

      // Try to find matching labels for the finding kind
      const kindLabelId = await resolveLabel(labels, finding.kind);
      const labelIds = kindLabelId ? [kindLabelId] : [];

      try {
        const result = await client.createIssue({
          teamId,
          title,
          description,
          priority: PRIORITY_MAP[finding.priority],
          labelIds,
        });

        const issueRef = result.issue;
        if (!issueRef) {
          console.error(`  Failed to create issue for finding ${i + 1}: no issue returned`);
          skipped++;
          continue;
        }
        // Resolve the lazy SDK reference, then re-fetch via useLinear for serializable type
        const resolved = await issueRef;
        const issue = await linear.getIssue(resolved.id);

        created.push({
          findingDisplayId: `IMP-${String(i + 1).padStart(4, "0")}`,
          linearIssueId: issue.id,
          identifier: issue.identifier,
          url: issue.url,
        });

        console.log(`  Created ${issue.identifier}: ${finding.summary}`);
      } catch (error) {
        console.error(`  Failed to create issue for finding ${i + 1}: ${error}`);
        skipped++;
      }
    }

    return { created, skipped };
  } finally {
    db.close();
  }
}
