import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";

const PROMPTS_DIR = "src/prompts";
const OUTPUT_PATH = "src/mdx.d.ts";

type PropState = "required" | "optional";

function classifyOptionality(source: string, prop: string): PropState {
  const escaped = prop.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const optionalPatterns = [
    new RegExp(`props\\.${escaped}\\s*(\\?|&&|\\|\\||\\?\\.|\\?\\?)`, "m"),
    new RegExp(`props\\.${escaped}\\s*(===|==|!==|!=)`, "m"),
    new RegExp(`\\bif\\s*\\(\\s*props\\.${escaped}\\b`, "m"),
  ];
  return optionalPatterns.some((pattern) => pattern.test(source))
    ? "optional"
    : "required";
}

function toComponentName(fileName: string): string {
  return basename(fileName, ".mdx").replace(/[^a-zA-Z0-9]+(.)/g, (_, char: string) =>
    char.toUpperCase(),
  );
}

function buildModuleDeclaration(fileName: string, source: string): string {
  const props = new Map<string, PropState>();
  const propMatches = source.matchAll(/props\.([A-Za-z_$][\w$]*)/g);

  for (const match of propMatches) {
    const prop = match[1];
    if (!prop) continue;
    const nextState = classifyOptionality(source, prop);
    const prev = props.get(prop);
    if (prev === "required" || nextState === "required") {
      props.set(prop, "required");
    } else {
      props.set(prop, "optional");
    }
  }

  const componentName = toComponentName(fileName);
  const interfaceName = `${componentName}PromptProps`;
  const lines = Array.from(props.entries())
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, state]) => `    ${name}${state === "optional" ? "?" : ""}: any;`);

  return [
    `declare module "*/prompts/${fileName}" {`,
    `  interface ${interfaceName} {`,
    ...lines,
    "  }",
    `  const Component: import("react").FC<${interfaceName}>;`,
    "  export default Component;",
    "}",
  ].join("\n");
}

async function main(): Promise<void> {
  const entries = await Array.fromAsync(new Bun.Glob("*.mdx").scan(PROMPTS_DIR));
  entries.sort();

  const declarations: string[] = [];
  for (const entry of entries) {
    const source = await readFile(join(PROMPTS_DIR, entry), "utf8");
    declarations.push(buildModuleDeclaration(entry, source));
  }

  const output = [
    "// AUTO-GENERATED by scripts/gen-mdx-types.ts — DO NOT EDIT",
    "// Regenerate: bun scripts/gen-mdx-types.ts",
    "//",
    `// Typed declarations for ${entries.length} MDX prompt files.`,
    "// Props extracted from prompt source by scanning `props.<name>` references,",
    "// so `tsc --noEmit` catches wrong names, missing props, and extras.",
    "",
    declarations.join("\n\n"),
    "",
  ].join("\n");

  await mkdir("src", { recursive: true });
  await writeFile(OUTPUT_PATH, output, "utf8");
}

await main();
