// AUTO-GENERATED by scripts/gen-mdx-types.ts — DO NOT EDIT
// Regenerate: bun scripts/gen-mdx-types.ts
//
// Typed declarations for 0 MDX prompt files.
// Props extracted from prompt source by scanning `props.<name>` references,
// so `tsc --noEmit` catches wrong names, missing props, and extras.


