// AUTO-GENERATED by scripts/gen-mdx-types.ts — DO NOT EDIT
// Regenerate: bun scripts/gen-mdx-types.ts
//
// Typed declarations for 9 MDX prompt files.
// Props extracted from prompt source by scanning `props.<name>` references,
// so `tsc --noEmit` catches wrong names, missing props, and extras.

declare module "*/prompts/CodeReview.mdx" {
  interface CodeReviewPromptProps {
    filesCreated?: any;
    filesModified?: any;
    qualityChecks?: any;
    unitCategory: any;
    unitId: any;
    unitName: any;
    whatWasDone?: any;
  }
  const Component: import("react").FC<CodeReviewPromptProps>;
  export default Component;
}

declare module "*/prompts/DiscoverIssues.mdx" {
  interface DiscoverIssuesPromptProps {
    entryType: any;
    focusAreas?: any;
    inferredPaths?: any;
    inputSignature: any;
    instruction: any;
    lens: any;
    lensChecklist?: any;
    lensMission: any;
    lensTitle: any;
    mode: any;
    rationale: any;
    risk: any;
    sliceId: any;
    slicePath: any;
  }
  const Component: import("react").FC<DiscoverIssuesPromptProps>;
  export default Component;
}

declare module "*/prompts/FinalReview.mdx" {
  interface FinalReviewPromptProps {
    acceptanceCriteria?: any;
    believesComplete?: any;
    buildPassed?: any;
    codeApproved?: any;
    codeSeverity?: any;
    description: any;
    failingSummary?: any;
    implSummary?: any;
    issuesResolved?: any;
    maxPasses: any;
    pass: any;
    prdApproved?: any;
    prdSeverity?: any;
    testsFailCount?: any;
    testsPassCount?: any;
    unitId: any;
    unitName: any;
  }
  const Component: import("react").FC<FinalReviewPromptProps>;
  export default Component;
}

declare module "*/prompts/LearningsExtraction.mdx" {
  interface LearningsExtractionPromptProps {
    branchPrefix?: any;
    codeReviewFeedback?: any;
    codeReviewIssues?: any;
    codeReviewSeverity?: any;
    finalReviewApproved?: any;
    finalReviewReasoning?: any;
    learningsFilePath: any;
    prdReviewFeedback?: any;
    prdReviewSeverity?: any;
    reviewFixFalsePositives?: any;
    reviewFixSummary?: any;
    unitCategory: any;
    unitId: any;
    unitName: any;
  }
  const Component: import("react").FC<LearningsExtractionPromptProps>;
  export default Component;
}

declare module "*/prompts/Implement.mdx" {
  interface ImplementPromptProps {
    acceptanceCriteria?: any;
    architectureRules?: any;
    branchPrefix?: any;
    commitPrefix?: any;
    contextFilePath: any;
    depSummaries?: any;
    emojiPrefixes?: any;
    evictionContext?: any;
    failingTests?: any;
    formatterCommands?: any;
    implementationGuidance?: any;
    implementationSteps?: any;
    planFilePath: any;
    previousImplementation?: any;
    reviewFeedback?: any;
    testWritingGuidance?: any;
    unitCategory: any;
    unitId: any;
    unitName: any;
    verifyCommands?: any;
  }
  const Component: import("react").FC<ImplementPromptProps>;
  export default Component;
}

declare module "*/prompts/Plan.mdx" {
  interface PlanPromptProps {
    acceptanceCriteria: any;
    branchPrefix?: any;
    commitPrefix?: any;
    contextFilePath: any;
    evictionContext?: any;
    inputSignature: any;
    planFilePath: any;
    researchSummary?: any;
    tddPatterns?: any;
    unitCategory: any;
    unitDescription: any;
    unitId: any;
    unitName: any;
  }
  const Component: import("react").FC<PlanPromptProps>;
  export default Component;
}

declare module "*/prompts/PrdReview.mdx" {
  interface PrdReviewPromptProps {
    acceptanceCriteria?: any;
    failingSummary?: any;
    filesCreated?: any;
    filesModified?: any;
    specChecks?: any;
    testResults?: any;
    unitCategory: any;
    unitId: any;
    unitName: any;
  }
  const Component: import("react").FC<PrdReviewPromptProps>;
  export default Component;
}

declare module "*/prompts/Research.mdx" {
  interface ResearchPromptProps {
    branchPrefix?: any;
    contextFilePath: any;
    evictionContext?: any;
    inputSignature: any;
    referenceFiles?: any;
    referencePaths?: any;
    relevantFiles?: any;
    rfcSections?: any;
    rfcSource?: any;
    unitCategory: any;
    unitDescription: any;
    unitId: any;
    unitName: any;
  }
  const Component: import("react").FC<ResearchPromptProps>;
  export default Component;
}

declare module "*/prompts/ReviewFix.mdx" {
  interface ReviewFixPromptProps {
    branchPrefix?: any;
    codeFeedback: any;
    codeIssues?: any;
    codeSeverity: any;
    commitPrefix?: any;
    emojiPrefixes?: any;
    specFeedback: any;
    specIssues?: any;
    specSeverity: any;
    unitCategory: any;
    unitId: any;
    unitName: any;
    validationCommands?: any;
  }
  const Component: import("react").FC<ReviewFixPromptProps>;
  export default Component;
}

declare module "*/prompts/Test.mdx" {
  interface TestPromptProps {
    branchPrefix?: any;
    filesCreated?: any;
    filesModified?: any;
    fixCommitPrefix?: any;
    testSuites?: any;
    unitCategory: any;
    unitId: any;
    unitName: any;
    whatWasDone?: any;
  }
  const Component: import("react").FC<TestPromptProps>;
  export default Component;
}
